### ISSUE TITLE
No need for header space when no text

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/youtubePlugin#10]
You can see that there is no carousel or WYSIWYG text and yet there is still a space for it at the top. 

Let's hide that space when there is no text or carousel. 

![screen shot 2015-08-24 at 10 15 01 am](https://cloud.githubusercontent.com/assets/2794086/9447128/93223d6e-4a4a-11e5-894f-9651e677c14f.png)

**Comment by sakshityagi** [comment]
Done. Please review.
