### ISSUE TITLE
Text cut off on control

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/youtubePlugin#11]
The Image carousel text seems to be cut off. 

![screen shot 2015-08-24 at 10 15 13 am](https://cloud.githubusercontent.com/assets/2794086/9447153/a6dd864c-4a4a-11e5-8630-98e3d4444666.png)

**Comment by sakshityagi** [comment]
This is due to some class that buildFire carousel library adds to this text. @DanielHindi Please look into this.

**Comment by jdm135** [comment]
@sakshityagi I'm not sure who implemented the carousel component, but the selector used was id="carousel". This was wrapped in <div class="item clearfix row">, when it shouldn't be. The carousel component injects the needed html inside id="carousel", so I just removed the extra html around it. 

@ianblair44 This should be fixed. Please confirm and close ticket.

**Comment by sakshityagi** [comment]
@jdm135 Its working fine now. Thanks.
