### ISSUE TITLE
BFW001-28  -  Youtube: Search field on active plugins not working

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#25]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 - Chrome

ACTUAL RESULTS:-
When user search for a plugin under active plugins, the search function won't return proper result unless you type in the plugin title in full and in exact same case. 

EXPECTED RESULTS:-
The search should be able to search plugins even is the search term used is just part of the title and should not be case sensitive. 

OTHER NOTES / ERROR MESSAGES:- 
email: gattesteracc_04@mailinator.com pass: test1234 

Video:
http://bugs8.gatserver.com/uploads/e91e81bc231b603c4db4f712dd6d7d12.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Active Plugin.
3. On the search box, type in a search term that is part of a plugin name. On the testing video I tried typing 'aldub'.
4. Notice that no results is being returned when there's actually 2 plugins with 'aldub' on its name. The plugin I'm searching will only show if I type in the plugin name in full and in exact same case

**Comment by ianblair44** [comment]
Moved to CS repo.
