### ISSUE TITLE
BFW001-59 - YouTube Plugin/ View -Preview of Body Content: After Preview of body content and clicking on Design tab generates warning Security of a sandboxed iframe is potentially compromised by allowing script and same origin access

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#26]
Priority: High
Reproducibility: Often
Device / OS / Browser / Version: Windows 7 Home Premium - IE 11

ACTUAL RESULTS:-
On YouTube Plugin, under Body Content, After clicking on View > Preview then clicking on Design tab, a warning 'Security of a sandboxed iframe is potentially compromised by allowing script and same origin access.' is generated on console log. 

EXPECTED RESULTS:- 
Using the View > Preview of body content does not generate console errors. 

OTHER NOTES / ERROR MESSAGES:- 
username:gattesteracc_16@mailinator.com password: test1234 

Video:
http://bugs8.gatserver.com/uploads/4fe327cbfbb1fe8fa46cb63ba63f5c47.mp4 
Log:
http://bugs8.gatserver.com/uploads/756ff6702c397f3a0aee16d4b5dcd253.txt

Steps to reproduce this issue
1. Open the link and login credentials
2. On the left menu, click on Plugin
3. Under Plugin, select Active Plugin
4. On the list of Plugin, click on Edit on YouTube Plugin
5. On body content, click on View then select Preview
6. The body content will be previewed then click on Design tab ( console errors generated is observed)

**Comment by ianblair44** [comment]
Moved to CS repo.
