### ISSUE TITLE
BFW001-39  -  All Plug ins: Clicking Home hyperlink doesn't do any actions or is not working

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#27]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:- 
Clicking Home hyperlink doesn't do any actions 

EXPECTED RESULTS:- 
Should make some actions or should work. 

OTHER NOTES / ERROR MESSAGES:- 
Desktop resolution is 1366x768 

username:gattesteracc_06@mailinator.com pass:test1234 

Video:
http://bugs8.gatserver.com/uploads/60cf652c61185849860d9a58660b0db4.mp4

Steps to reproduce this issue
1. Log in and add all the plugins that are in scope.
2. On the active plugin select the added plugin one by one.
3. Click the Home hyperlink inside every plugin.
4. Notice that Home hyperlink doesn't do any action or doesn't work.

**Comment by sakshityagi** [comment]
@ianblair44 This issue will be addressed by BuildFire.
