### ISSUE TITLE
BFW001-17  -  Youtube: Share link from the app preview not working

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#28]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 - Chrome

ACTUAL RESULTS:-
When user view the added youtube video plugin from the app viewer, the share button is not working. 

EXPECTED RESULTS:- 
Share button should work from the viewer. 

OTHER NOTES / ERROR MESSAGES:- 
email: gattesteracc_04@mailinator.com pass: test1234 

Video:
http://bugs8.gatserver.com/uploads/3ccdaf01cbed5dd1304a99c502008eff.mp4 
Screenshot:
http://bugs8.gatserver.com/uploads/6a6c948681ed7f2d95b6dca39e06e891.jpg

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Side Menu.
3. From the app preview, select the youtube video plugin and it will open the video from the viewer.
4. Click on the 'share' link and notice that nothing happens when clicked.

**Comment by sakshityagi** [comment]
@ianblair44 To be provided by BuildFire.

**Comment by sakshityagi** [comment]
@ianblair44 any updates on this?

**Comment by nathankeating** [comment]
Removed it for now

**Comment by nathankeating** [comment]
@ianblair44 Please close
