### ISSUE TITLE
BFW001-32  -  Search function when adding plugin instance on side menu structure not working.

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#29]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 - Chrome

ACTUAL RESULTS:-
When user search for in the Side Menu structure - Add/Edit action panel, the search function won't return proper result unless you type in the plugin title in full and in exact same case. 

EXPECTED RESULTS:- 
The search should be able to search plugins even is the search term used is just part of the title and should not be case sensitive. 

OTHER NOTES / ERROR MESSAGES:- 
email: gattesteracc_04@mailinator.com pass: test1234 

Video:
http://bugs8.gatserver.com/uploads/ff46ac0ce3cb560641b5f52a7cf5c44d.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Side Menu.
3. Click on 'Add Plugin Instance' button to add plugin instance and an 'add/edit action' form will open.
4. On the search box type in a search term that is part of a plugin's name.
5. Notice that the search function doesn't return the correct results. It requires the user to type in the plugin title in full and exact same case to be able to return a search result.

**Comment by ianblair44** [comment]
Moved to CS repo.
