### ISSUE TITLE
BFW001-50  -  Youtube: Text entered into the WYSIWYG editor does not appear on the app's page

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#30]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 10 - Chrome

ACTUAL RESULTS:-
Text entered into the WYSIWYG editor does not appear on the app's page 

EXPECTED RESULTS:- 
Text entered into the WYSIWYG editor appear on the app's page 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_11@mailinator.com	password: test1234 

Screen resolution: 1600x900 

Screenshots:
http://bugs8.gatserver.com/uploads/e6e60c771a33997a6ab4965225510ec9.jpg http://bugs8.gatserver.com/uploads/6fadeaa61cd479cfba2a8bfb3d1b102e.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add youtubePlugin
4. Enter something for the plugin title
5. Enter a valid youtube url
6. In the WYSIWYG Text field, enter something and try to find it on the app's display

**Comment by sandeepchhapola** [comment]
@ianblair44 In Screenshots selected content type is 'single video' so for single video we showed description of video item. The text entered into the WYSIWYG editor will be appeared when content type is 'Channel Feed'.

**Comment by ianblair44** [comment]
@sandeepchhapola you are correct and this was done by design. This technically isn't a bug.
