### ISSUE TITLE
BFW001-1  -  Youtube: The 'more information' link shows nothing, a "dynamically injected" label is displayed

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#31]
Priority: Medium
Reproducability: Always
Device / OS / Browser / Version: Windows 7 / Google

ACTUAL RESULTS:- 
When user clicks on 'more information' link under youtube plugin, the page only shows 'dynamically injected'. 

EXPECTED RESULTS: 
Page should show details about the youtube plugin. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_04@mailinator.com pass: test1234 

http://bugs8.gatserver.com/uploads/e7905e100a485fc1155a444039ade03d.mp4

Steps to reproduce this issue
1.Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the side menu, select Plugins > Add Plugin.
3. On the youtube plugin, select on 'more information' link
4. Notice that page redirects to a page that only says 'dynamically injected'.

**Comment by ianblair44** [comment]
Moved to CS repo.
