### ISSUE TITLE
BFW001-3  -  Youtube: Incorrect video URL is successfully validated

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#32]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 / Google chrome

ACTUAL RESULTS:- 
When adding the youtube plugin, user must add a youtube url and validate it. However, adding an incorrect url is validated successfully by the form. 

EXPECTED RESULTS: 
Form should be able to accurately identify if the url is valid or not. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_04@mailinator.com 

pass: test1234 

http://bugs8.gatserver.com/uploads/554342b94eba26d66ebdc1c233d748e8.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Add Plugin.
3. From the list, select Youtube by clicking on 'add plugin'.
4. Add an incorrect url on the url field then click validate.
5. Notice that the form successfully validates the url even if the url is incorrect or would actually return no video.

**Comment by sakshityagi** [comment]
This should be working fine now. Please close if fixed.
