### ISSUE TITLE
BFW001-4  -  Youtube Plug-in/Desgn: Clicking to add an image opens more than one Media Gallery windows

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#33]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8.1 Chrome Version 45

ACTUAL RESULTS:- 
Clicking to add an image opens more than one Media Gallery windows. 

EXPECTED RESULTS: 
Only one window should open. 

OTHER NOTES / ERROR MESSAGES:- 

Username: gattesteracc_17@mailinator.com Password: test1234 

Screen resolution: 1366x768. 

Please find attached a video of the issue: 

http://bugs8.gatserver.com/uploads/aa7b21a625dca3f2833499eb82dc9095.mp4

Steps to reproduce this issue
1. Navigate to http://int2.myapp.buildfire.com/#/addPlugin.
2. Click the "Add" button to add a Youtube plug-in .
3. Click "Design".
4. Click to add an "Item List Background Image".
5. Observe more than one windows open.

**Comment by sakshityagi** [comment]
@ianblair44 This behavior is with all the image lib components. Pop ups are opened multiple times. Must be some issue with sdk.

**Comment by ianblair44** [comment]
Daniel says it's being called multiple times. It may be related to the people plugin and media center issue where it is not unbinding.

**Comment by sakshityagi** [comment]
@ianblair44 This is fixed now. Please review and let me know if its still an issue.
