### ISSUE TITLE
BFW001-12  -  Active Plugins: Delete condition is case sensitive

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#34]
Priority: Usability
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 / Google Chrome

ACTUAL RESULTS:- 
When user tries to delete a created plugin from the active plugins menu, it requires user to type in the word 'delete' to be able to delete the plugin. However, when user typed 'delete' in any case rather than All caps, the plugin cannot be deleted. 

EXPECTED RESULTS: 
The 'delete' condition should not be case sensitive. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_04@mailinator.com pass: test1234 

http://bugs8.gatserver.com/uploads/1cd5e8d5b4b65baf1636437e7e94460c.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Active Plugins.
3. From this select any plugin created and then click on 'delete'.
4. You will be prompted to type 'delete' in order to successfully delete the plugin.
5. When user types 'delete' in different case rather than ALL caps, the plugin cannot be deleted.

**Comment by ianblair44** [comment]
Moved to CS repo.
