### ISSUE TITLE
BFW001-52  -  Plugin help text does not make sense

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#35]
Priority: Low
Reproducibility: Always
Device / OS / Browser / Version: Windows 10, Chrome

ACTUAL RESULTS:-
All the active plugin have irrelevant help text: "Listen all day to our awesome radio stations. Listen all day to our awesome radio stations." 

EXPECTED RESULTS: 
The active plugin should use help text that is relevant. 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_11@mailinator.com	
password: test1234 

Screen resolution: 1600x900 

http://bugs8.gatserver.com/uploads/83e0d342c8e127601aa939e3a34daf63.jpg http://bugs8.gatserver.com/uploads/cf67235f80c9830eac797e5378f42b9d.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Active Plugins

**Comment by sakshityagi** [comment]
@ianblair44 This issue will be addressed by BuildFire.
