### ISSUE TITLE
BFW001-20  -  youtubePlugin label must be changed to Youtube for consistency

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#36]
Priority: Low
Reproducability: Always
Device / OS / Browser / Version: Windows 7 - Chrome

ACTUAL RESULTS:- 
Youtube plugin is named "youtubePlugin" 

EXPECTED RESULTS: 
Label should be Youtube plugin 

OTHER NOTES / ERROR MESSAGES:- 

gattesteracc_20@mailinator.com test1234 

Screen resolution - 1366x768 

http://bugs8.gatserver.com/uploads/a64a9d8088fb4a9ef8dc3e5ea9afb06f.jpg

Steps to reproduce this issue
1. Access Buildfire
2. Go to Plugins > Add Plugin

**Comment by sakshityagi** [comment]
@ianblair44 Should be fixed now.
