### ISSUE TITLE
BFW001-23  -  Plugin does not disappear when deleted and it is still interact-able

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#37]
Priority: Medium
Reproducibility: Often
Device / OS / Browser / Version: Win 7 Ult x64, Chrome and Firefox

ACTUAL RESULTS:- 
Plugin does not disappear when deleted by copy/pasting the word "DELETE" in the prompted text box and is still interact-able. 

EXPECTED RESULTS:- 
The plugin should disappear once deleted. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_05@mailinator.com
password: test1234 

Reviewed on following resolutions: 1920x1200 and 1366x768 

Issue occurs 7/10 when you have more than 3 plugins. Can still occur with less. 

http://bugs8.gatserver.com/uploads/99d62b538d882e02af3cd6a5d4e25183.mp4

Steps to reproduce this issue
1. Add at least 3 different plugins 
2. Proceed to Plugins-> Active Plugins
3. Press Delete on one of the plugins
4. When prompted, copy/paste "DELETE" in the text box
5. Observe that Plugin is still available and usable

**Comment by ianblair44** [comment]
Reference in another ticket in CS.
