### ISSUE TITLE
BFW001-24  -  Youtube - Uncheck function on adding plug instance not working

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#38]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 / Google Chrome

ACTUAL RESULTS:- 
When user add plugin instance on the side menu structure page, once a plugin from the list is checked and unchecked, the plugin will still show on the selected list. This makes unticking the checkbox not functional. 

EXPECTED RESULTS: 
Form should only add plugins that were selected before the apply button is clicked. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_04@mailinator.com 
pass: test1234 

http://bugs8.gatserver.com/uploads/3534d0b0f306ce4b665fa40d3b739296.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Side Menu.
3. On the Side Menu Structure page, click on 'add plugin instance'.
4. Select a video from the list by ticking the checkbox. 
5. Before clicking on the 'apply' button, untick a video from the list and then click the 'apply' button.
6. Notice that even if the video was unticked prior to click the apply button, the video is still on the list of selected instance.

**Comment by ianblair44** [comment]
Moved to CS repo.
