### ISSUE TITLE
BFW001-64  -  ActivePlugins - Delete: Prompt display's "DELETE is spelled incorrectly" although user doesn't type anything in the text box

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#39]
Priority: Low
Reproducability: Always
Device / OS / Browser / Version: Windows 8 /Chrome

ACTUAL RESULTS:- 
Prompt display's "DELETE is spelled incorrectly" although user doesn't type anything (in order for something to be spelled incorrectly) 

EXPECTED RESULTS: 
Should display correct prompt. 

OTHER NOTES / ERROR MESSAGES:- 

Username:gattesteracc_06@mailinator.com 
pass:test1234 

desktop resolution is 1366x768 

http://bugs8.gatserver.com/uploads/386552059b12dcbb40896956c1307c2e.mp4 

http://bugs8.gatserver.com/uploads/54e4af8c2354e47bec5de989f20a9bf6.log

Steps to reproduce this issue
1. Log in and add plug in.
2. On the active plug in delete a plug in.
3. On the confirmation prompt don't type any.
4. Select delete without typing anything.
5. Notice that prompt displays "DELETE is spelled incorrectly" although user doesn't type any.

**Comment by ianblair44** [comment]
Won't fix.
