### ISSUE TITLE
BFW001-58  -  (Gray Area - Unknown Expected Behaviour) YouTube Plugin - Body Content - Inserting special characters generates console error

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#40]
Priority: Medium
Reproducibility: Often
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:- 
Adding special characters using the Insert/Edit Image option on the body content generate console error 'Object doesn't support this action'. 

EXPECTED RESULTS: 
Special characters can be inserted in the body content without generating console error. 

OTHER NOTES / ERROR MESSAGES:- 

username:gattesteracc_16@mailinator.com password: test1234 

http://bugs8.gatserver.com/uploads/e10c6fe1549c16f20f6d3d8f30eb71eb.mp4 

http://bugs8.gatserver.com/uploads/b4d527cd2f148239696b5bf11b0d9221.txt

Steps to reproduce this issue
1. Open the site link and login
2. On the left side menu, click on Plugin
3. Under Plugin click on Active Plugin
4. On the list of created Plugins, click on edit on YouTube Plugin 
5. On Content, go to Body Content then click on Insert/Edit Image
6. Click on Special Characters then select character to insert ex. heart  (notice that the console error 'Object doesn't support this action' is generated)

**Comment by ianblair44** [comment]
Moved to CS repo.
