### ISSUE TITLE
BFW001-67  -  When plugin name is too long it's overlapped with Edit button

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/youtubePlugin#41]
Priority: Low
Reproducibility: Always
Device / OS / Browser / Version: Windows 8.1, Chrome 45.0.2454.85 m, IE11

ACTUAL RESULTS:- 
Edit button covers the name of plugin 

EXPECTED RESULTS: 
Plugin name is fully shown 

OTHER NOTES / ERROR MESSAGES:- 

login: gattesteracc_13@mailinator.com	test1234 

screen resolution - 1366x768 

http://bugs8.gatserver.com/uploads/1675344b3581bffc2f46e45b4fc2176c.jpg

Steps to reproduce this issue
1. Login to http://int2.myapp.buildfire.com
2. Add new plugin
3. Name new plugin as 'http://www.youtube.com/playlist?list=PLJMRN_6MT0JYItlUeor7YRa0r6-lI8MMR'
4. Save plugin
5. Open the list of active plugins
6. Observe the added plugin

**Comment by ianblair44** [comment]
Moved to CS repo.
