### ISSUE TITLE
CP VIMEO - Channel Feed vs User Feed vs Single video is confusing. Add tooltip to clarify.

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/youtubePlugin#42]
Channel Feed vs User Feed vs Single video is confusing. Add tooltip to clarify.

**Comment by ianblair44** [comment]
We should just show example feeds for each option underneath the input box.

**Comment by nathankeating** [comment]
That would be fine. As long as we clarify what they are.

**Comment by ianblair44** [comment]
referenced in another ticket in this repo.
