### ISSUE TITLE
CP VIMEO - Incorrect text

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/youtubePlugin#45]
“Having problems with your feed…” should be changed to show them how they should format the feed URLs

**Comment by ianblair44** [comment]
Can you give us the text you would like and then log it in the Vimeo repo?

**Comment by nathankeating** [comment]
Yes. I have logged in the Vimeo repo here: https://github.com/BuildFire/vimeoPlugin/issues/18

**Comment by sandeepchhapola** [comment]
@nathankeating you mean if I've selected Channel Feed radio button then text will be "Having problems with your channel feed url format? Ensure that is a valid channel feed by naming it through an RSS feed validator Here."?

**Comment by ianblair44** [comment]
@sandeepchhapola we are going to replace this text. 

"Having problems with your channel feed url format? Ensure that is a valid channel feed by naming it through an RSS feed validator Here."

With this. 

"
Channel Feed - https://vimeo.com/channels/pmg
User Feed - http://vimeo.com/gopro
Single Video- https://vimeo.com/130824206
"

**Comment by sandeepchhapola** [comment]
ok

**Comment by nathankeating** [comment]
Yes. Thanks, Ian.

@sandeepchhapola Let's make it say this:

Channel Feed Example: https://vimeo.com/channels/pmg
User Feed Example: http://vimeo.com/gopro
Single Video Example: https://vimeo.com/130824206

**Comment by sandeepchhapola** [comment]
resolved in vimeo issue- Incorrect text #18

**Comment by sakshityagi** [comment]
Please close the issue if fixed.
