### ISSUE TITLE
CP YOUTUBE - "Single Video" selection

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/youtubePlugin#48]
If “Single Video” is selected, the carousel and wysiwyg should hide because the user should be taken right into the item details

**Comment by ianblair44** [comment]
Hide on the Control side?

**Comment by nathankeating** [comment]
Yes. Since the item list will be bypassed, this carousel and wysiwyg will not be displayed.

Therefore, when "single video" is selected, hide them on the editor (control).

NOTE: Do not delete or remove any content the app owner has already implemented on the carousel or wysiwyg. Just hide them.

**Comment by nathankeating** [comment]
Let's hold off on this for now. We can readdress it in the future if we need.
