### ISSUE TITLE
Gap above feed items when removing text from WYSIWYG

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/youtubePlugin#51]
When you add text for the WYSIWYG it works just fine. 

![screen shot 2015-09-23 at 9 03 21 pm](https://cloud.githubusercontent.com/assets/2794086/10065178/b7f80c46-6236-11e5-8ec8-d7fa0478fa1f.png)

However, once you remove the text, the space above the feed doesn't go away. 

![screen shot 2015-09-23 at 9 03 38 pm](https://cloud.githubusercontent.com/assets/2794086/10065182/c2cbcf0e-6236-11e5-9cc6-56fa908b8386.png)

**Comment by ianblair44** [comment]
The same issue is happening on Vimeo.

**Comment by sakshityagi** [comment]
@ianblair44 Fixed now. Please review.
